# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [3]:
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [78]:
one_d = np.array([26,72,55])
two_d = np.array([[1,2,3],[2,3,4]])
three_d = np.array([[[1,2,3],[2,3,4],[3,4,5]],[[10,20,30],[20,30,40],[30,40,50]]])

print("one_d",one_d)
print("two_d",two_d)
print("three_d",three_d)


one_d [26 72 55]
two_d [[1 2 3]
 [2 3 4]]
three_d [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[10 20 30]
  [20 30 40]
  [30 40 50]]]


In [80]:
# Each set gives the same output

# In 1d array [start:end] gets items from start to end (end is not included)
# In 2d array [start:end] gets the rows
# In 3d array [start:end] gets the 2-d matrices

print(one_d[0:3])
print(one_d[0:])

print(one_d[0:2])
print(one_d[:2])



[26 72 55]
[26 72 55]
[26 72]
[26 72]


In [81]:
print(two_d)
print(two_d[0:])
print(two_d[0:3])



[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]]


In [102]:
print(three_d)
print(three_d[0:])

print(three_d[1:])

print(three_d[:1])



[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[10 20 30]
  [20 30 40]
  [30 40 50]]]
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[10 20 30]
  [20 30 40]
  [30 40 50]]]
[[[10 20 30]
  [20 30 40]
  [30 40 50]]]
[[[1 2 3]
  [2 3 4]
  [3 4 5]]]


In [32]:
# slicing array so that one element is returned
print(one_d[-1])
print(one_d[2])

print(two_d[-1,-1])
print(two_d[1,0])
    
print(three_d[-1,-1,-1])
print(three_d[1,0,1])


55
55
4
2
50
20


In [136]:
# slicing array so that a dimension is returned
print(one_d[1,])

# extracting a row
print(two_d[1,])

# extracting a column
print(two_d[:,1])

# extracting the first dimension
print(three_d[0,])
print(three_d[1,])

# extracting the columns from each 2d matrices
print(three_d[:,1])

# extracting the columns from one of the 2d matrices
print(three_d[1:,2])

# extracting the element in 3rd row and 3rd column of the selected 2d matrices
print(three_d[1:,2,2])
print(three_d[:,2,2])

print(three_d[1,:2,2])


72
[2 3 4]
[2 3]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[10 20 30]
 [20 30 40]
 [30 40 50]]
[[ 2  3  4]
 [20 30 40]]
[[30 40 50]]
[50]
[ 5 50]
[30 40]


In [107]:
# difference between [x:] and [x,..]
# [x:] preserves the original dimension

print(one_d[1:])
print(one_d[1,])

print(three_d[1,])
print(three_d[1,].shape)
print(three_d[1,].ndim)

print(three_d[1:])
print(three_d[1:].shape)
print(three_d[1:].ndim)

[72 55]
72
[[10 20 30]
 [20 30 40]
 [30 40 50]]
(3, 3)
2
[[[10 20 30]
  [20 30 40]
  [30 40 50]]]
(1, 3, 3)
3


## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [156]:
bool_demo = np.random.random((5,2))

print(bool_demo)
#print(bool_demo<0.5)
#print(bool_demo>0.5)
#print(bool_demo<=0.5)
#print(bool_demo==0.5)
print((bool_demo<0.5) & (bool_demo>0.3))

print((bool_demo>0.5) | (bool_demo<0.3))

print(bool_demo[(bool_demo>0.5) | (bool_demo<0.3)])

[[0.40176123 0.12600821]
 [0.88904365 0.02192448]
 [0.91170991 0.94425188]
 [0.51849824 0.25620194]
 [0.12589029 0.01580686]]
[[ True False]
 [False False]
 [False False]
 [False False]
 [False False]]
[[False  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
[0.12600821 0.88904365 0.02192448 0.91170991 0.94425188 0.51849824
 0.25620194 0.12589029 0.01580686]


## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [ ]:
#help(np.transpose)
#help(np.reshape)
#help(np.resize)


In [190]:
print(two_d)
# transpose of a 2-d matrix - 
# can be obtained as two_d.T
print(np.transpose(two_d))


# changes the array into any shape 
# there are settings as to how to read the elements for changing the shape
print(np.reshape(two_d,(3,2)))
print(np.reshape(three_d,(9,2)))


# changes the shape of an array into shape specified
# when it runs out of elements, it reuses the elements of the array again
print(np.resize(two_d,(1,10)))
print(np.resize(three_d,(2,9)))
print(np.resize(three_d,(3,9)))




[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]
[[1 2]
 [3 2]
 [3 4]]
[[ 1  2]
 [ 3  2]
 [ 3  4]
 [ 3  4]
 [ 5 10]
 [20 30]
 [20 30]
 [40 30]
 [40 50]]
[[1 2 3 2 3 4 1 2 3 2]]
[[ 1  2  3  2  3  4  3  4  5]
 [10 20 30 20 30 40 30 40 50]]
[[ 1  2  3  2  3  4  3  4  5]
 [10 20 30 20 30 40 30 40 50]
 [ 1  2  3  2  3  4  3  4  5]]


In [201]:
# help(np.ravel)
# help(np.append)

In [198]:
print(two_d)

print(np.ravel(two_d))
print(two_d.reshape(-1))

print(np.ravel(two_d.T))
print(np.ravel(two_d,order="F"))


[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]
[1 2 3 2 3 4]
[1 2 2 3 3 4]
[1 2 2 3 3 4]


## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [202]:
print(two_d)
print(np.transpose(two_d))
print(two_d.T)

[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]
[[1 2]
 [2 3]
 [3 4]]


## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [212]:
print(two_d)
print(np.resize(two_d,(2,5)))
print(np.resize(two_d,(3,3)))

matrix_a = np.random.random((8,2))
print(matrix_a)
print(np.reshape(matrix_a,(4,4)))

[[1 2 3]
 [2 3 4]]
[[1 2 3 2 3]
 [4 1 2 3 2]]
[[1 2 3]
 [2 3 4]
 [1 2 3]]
[[0.28286362 0.3431937 ]
 [0.20979871 0.22349209]
 [0.71103686 0.99588537]
 [0.44326207 0.83119929]
 [0.35408742 0.39221686]
 [0.0627387  0.86950108]
 [0.05329236 0.95321954]
 [0.37992688 0.72974466]]
[[0.28286362 0.3431937  0.20979871 0.22349209]
 [0.71103686 0.99588537 0.44326207 0.83119929]
 [0.35408742 0.39221686 0.0627387  0.86950108]
 [0.05329236 0.95321954 0.37992688 0.72974466]]


## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [223]:
print(three_d)
print(np.append(three_d,[[[6,7,8],[60,70,80],[600,700,800]]],axis=0))
print(np.append(three_d,[[[6,7,8]],[[60,70,80]]],axis=1))
print(np.append(three_d,[[[6],[7],[8]],[[60],[70],[80]]],axis=2))

[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[10 20 30]
  [20 30 40]
  [30 40 50]]]
[[[  1   2   3]
  [  2   3   4]
  [  3   4   5]]

 [[ 10  20  30]
  [ 20  30  40]
  [ 30  40  50]]

 [[  6   7   8]
  [ 60  70  80]
  [600 700 800]]]
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]
  [ 6  7  8]]

 [[10 20 30]
  [20 30 40]
  [30 40 50]
  [60 70 80]]]
[[[ 1  2  3  6]
  [ 2  3  4  7]
  [ 3  4  5  8]]

 [[10 20 30 60]
  [20 30 40 70]
  [30 40 50 80]]]


## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

In [277]:
#help(np.insert)
help(np.delete)

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : slice, int or array of ints
        Indicate indices of sub-arrays to remove along the specified axis.
    
        .. versionchanged:: 1.19.0
            Boolean indices are now treated as a mask of elements to remove,
            rather than being cast to the integers 0 and 1.
    
    axis : int, optional
        The axis along which to delete the subarray defined by `obj`.
        If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also

In [275]:
array = np.array([[1,1],[2,2],[3,3]])
print(array)

# np.insert( array, position, value to insert, axis)
# if axis in not specified, array is first flattened

print(np.insert(array,2,5))
print(np.insert(array,2,5,axis=0))
print(np.insert(array,2,5,axis=1))

print(np.insert(array,2,[10,50],axis=0))
print(np.insert(array,1,[10,50,100],axis=1))



[[1 1]
 [2 2]
 [3 3]]
[1 1 5 2 2 3 3]
[[1 1]
 [2 2]
 [5 5]
 [3 3]]
[[1 1 5]
 [2 2 5]
 [3 3 5]]
[[ 1  1]
 [ 2  2]
 [10 50]
 [ 3  3]]
[[  1  10   1]
 [  2  50   2]
 [  3 100   3]]


In [281]:
# np.delete(array, position, axis)
# if axis is not specified, array is flattened

print(array)

print(np.delete(array,0,axis=0)) 
print(np.delete(array,0,axis=1)) 



[[1 1]
 [2 2]
 [3 3]]
[[2 2]
 [3 3]]
[[1]
 [2]
 [3]]


## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [286]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack 1-d arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_array, my_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [ ]:
#help(np.column_stack)

## Task 5d: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [297]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array,1))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]])]


In [295]:
#help(np.hsplit)